#!/usr/bin/env python
"""Generate whestbench API + CLI reference MDX, and verify doc coverage.

Usage:
    python scripts/generate_docs.py            # generate API + CLI MDX
    python scripts/generate_docs.py --verify   # check coverage only (no writes)
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEBSITE = ROOT / "website"
API_DIR = WEBSITE / "content" / "docs" / "api"
CLI_DIR = WEBSITE / "content" / "docs" / "cli"
GENERATED_DIR = WEBSITE / ".generated"
REPO_BLOB = "https://github.com/AIcrowd/whestbench/blob/main"


def public_symbols() -> list[tuple[str, object]]:
    mod = importlib.import_module("whestbench")
    return [(name, getattr(mod, name)) for name in mod.__all__]


def symbol_kind(obj: object) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isroutine(obj):
        return "function"
    return "value"


def signature_str(name: str, obj: object) -> str:
    try:
        return f"{name}{inspect.signature(obj)}"  # pyright: ignore[reportArgumentType]
    except (TypeError, ValueError):
        return name


def source_link(obj: object) -> str | None:
    target = inspect.unwrap(obj) if callable(obj) else obj
    try:
        src_file = inspect.getsourcefile(target)  # pyright: ignore[reportArgumentType]
        _, lineno = inspect.getsourcelines(target)  # pyright: ignore[reportArgumentType]
    except (TypeError, OSError):
        return None
    if not src_file:
        return None
    try:
        rel = Path(src_file).resolve().relative_to(ROOT)
    except ValueError:
        return None
    return f"{REPO_BLOB}/{rel.as_posix()}#L{lineno}"


def docstring(obj: object) -> str:
    return inspect.getdoc(obj) or ""


def _slug(name: str) -> str:
    return name.lower()


def _first_line(text: str) -> str:
    line = text.strip().splitlines()[0] if text.strip() else ""
    return line[:157] + "…" if len(line) > 158 else line


def render_api_page(name: str, obj: object) -> str:
    kind = symbol_kind(obj)
    sig = signature_str(name, obj)
    doc = docstring(obj)
    link = source_link(obj)
    desc = _first_line(doc) or f"{kind} {name}"
    lines = [
        "---",
        f"title: {name}",
        f"description: {json.dumps(desc)}",
        "---",
        "",
        f"`{kind}`" + (f" · [source]({link})" if link else ""),
        "",
        "```python",
        sig,
        "```",
        "",
    ]
    if doc:
        lines += ["```text", doc, "```", ""]
    return "\n".join(lines)


def write_api() -> list[Path]:
    API_DIR.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    index_rows: list[str] = []
    pages: list[str] = ["index"]
    for name, obj in sorted(public_symbols(), key=lambda t: t[0].lower()):
        slug = _slug(name)
        page = API_DIR / f"{slug}.mdx"
        page.write_text(render_api_page(name, obj), encoding="utf-8")
        written.append(page)
        pages.append(slug)
        index_rows.append(
            f"- [`{name}`]({slug}) — {_first_line(docstring(obj)) or symbol_kind(obj)}"
        )

    index = (
        "---\ntitle: API Reference\n"
        "description: Autogenerated reference for the whestbench public API.\n---\n\n"
        "# API Reference\n\n"
        "Every symbol exported from `whestbench` (`__all__`). Generated from source.\n\n"
        + "\n".join(index_rows)
        + "\n"
    )
    (API_DIR / "index.mdx").write_text(index, encoding="utf-8")
    (API_DIR / "meta.json").write_text(
        json.dumps({"title": "API", "pages": pages}, indent=2) + "\n", encoding="utf-8"
    )
    return written


def cli_parser() -> argparse.ArgumentParser:
    cli = importlib.import_module("whestbench.cli")
    return cli._build_participant_parser()  # pyright: ignore[reportAttributeAccessIssue]


def iter_subcommands(parser: argparse.ArgumentParser):
    for action in parser._actions:  # pyright: ignore[reportAttributeAccessIssue]
        if isinstance(action, argparse._SubParsersAction):  # pyright: ignore[reportAttributeAccessIssue]
            help_by_name = {sa.dest: sa.help for sa in action._get_subactions()}  # pyright: ignore[reportAttributeAccessIssue]
            for name, sub in action.choices.items():
                help_text = help_by_name.get(name)
                if help_text == argparse.SUPPRESS:
                    continue
                yield name, sub, help_text


def _options(subparser: argparse.ArgumentParser):
    for act in subparser._actions:  # pyright: ignore[reportAttributeAccessIssue]
        if isinstance(act, (argparse._HelpAction, argparse._SubParsersAction)):  # pyright: ignore[reportAttributeAccessIssue]
            continue
        if act.help == argparse.SUPPRESS:
            continue
        flag = ", ".join(act.option_strings) or (act.metavar or act.dest)
        if act.default is None or act.default is False or act.default is argparse.SUPPRESS:
            default = ""
        else:
            default = repr(act.default)
        yield flag, default, (act.help or "")


def _nested(subparser: argparse.ArgumentParser):
    return list(iter_subcommands(subparser))


def render_cli_page(name: str, subparser: argparse.ArgumentParser, help_text: str | None) -> str:
    desc = (help_text or "").strip()
    lines = [
        "---",
        f"title: whest {name}",
        f"description: {json.dumps(desc or f'whest {name} command')}",
        "---",
        "",
        f"# `whest {name}`",
        "",
        desc,
        "",
        "```text",
        f"whest {name} [options]",
        "```",
        "",
    ]

    def _opts_table(sp: argparse.ArgumentParser) -> list[str]:
        rows = [
            f"| `{flag}` | {('`' + d + '`') if d else ''} | {h} |" for flag, d, h in _options(sp)
        ]
        if not rows:
            return []
        return ["| Option | Default | Description |", "| --- | --- | --- |", *rows, ""]

    nested = _nested(subparser)
    if nested:
        for sub_name, sub_parser, sub_help in nested:
            lines += [f"## `whest {name} {sub_name}`", "", (sub_help or "").strip(), ""]
            lines += _opts_table(sub_parser)
    else:
        lines += _opts_table(subparser)
    return "\n".join(lines)


def write_cli() -> list[Path]:
    CLI_DIR.mkdir(parents=True, exist_ok=True)
    parser = cli_parser()
    written: list[Path] = []
    pages: list[str] = ["index"]
    index_rows: list[str] = []
    for name, sub, help_text in iter_subcommands(parser):
        slug = _slug(name)
        (CLI_DIR / f"{slug}.mdx").write_text(
            render_cli_page(name, sub, help_text), encoding="utf-8"
        )
        written.append(CLI_DIR / f"{slug}.mdx")
        pages.append(slug)
        index_rows.append(f"- [`whest {name}`]({slug}) — {(help_text or '').strip()}")

    index = (
        "---\ntitle: CLI Reference\n"
        "description: Autogenerated reference for the whest command-line interface.\n---\n\n"
        "# CLI Reference\n\nGenerated from the `whest` argparse definition.\n\n"
        + "\n".join(index_rows)
        + "\n"
    )
    (CLI_DIR / "index.mdx").write_text(index, encoding="utf-8")
    (CLI_DIR / "meta.json").write_text(
        json.dumps({"title": "CLI", "pages": pages}, indent=2) + "\n", encoding="utf-8"
    )
    return written


def verify() -> list[str]:
    problems: list[str] = []
    for name, obj in public_symbols():
        if not docstring(obj):
            problems.append(f"API symbol `{name}` has no docstring")
    for name, sub, help_text in iter_subcommands(cli_parser()):
        if not (help_text or "").strip():
            problems.append(f"CLI command `whest {name}` has no help text")
        for flag, _default, help_str in _options(sub):
            if not help_str.strip():
                problems.append(f"CLI option `whest {name} {flag}` has no help text")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="Check coverage only; no writes")
    args = parser.parse_args(argv)

    if args.verify:
        problems = verify()
        if problems:
            print("Doc coverage failures:")
            for p in problems:
                print(f"  - {p}")
            return 1
        print("Doc coverage OK")
        return 0

    api = write_api()
    cli = write_cli()
    print(f"Generated {len(api)} API pages and {len(cli)} CLI pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
