#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"

STATE_FILE_DEFAULT="$ROOT_DIR/.aicrowd/sanitization/public-sync-state.local.env"
STATE_EXAMPLE_FILE_DEFAULT="$ROOT_DIR/.aicrowd/sanitization/public-sync-state.example.env"
SENSITIVE_MANIFEST_DEFAULT="$ROOT_DIR/.aicrowd/sanitization/sensitive-paths.txt"
EXCLUDE_FILE_DEFAULT="$ROOT_DIR/.aicrowd/sanitization/public-sync-excludes.txt"
BLOB_REPLACEMENTS_DEFAULT="$ROOT_DIR/.aicrowd/sanitization/blob-replacements.txt"

STATE_FILE="$STATE_FILE_DEFAULT"
STATE_EXAMPLE_FILE="$STATE_EXAMPLE_FILE_DEFAULT"
SENSITIVE_MANIFEST="$SENSITIVE_MANIFEST_DEFAULT"
EXCLUDE_FILE="$EXCLUDE_FILE_DEFAULT"
BLOB_REPLACEMENTS="$BLOB_REPLACEMENTS_DEFAULT"

PUBLIC_REMOTE="public"
PUBLIC_BRANCH="main"
LAST_INGESTED_PUBLIC_SHA=""
LAST_SYNC_UTC=""

trim_line() {
  printf '%s' "$1" | sed -E 's/[[:space:]]*#.*$//; s/^[[:space:]]+//; s/[[:space:]]+$//'
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

usage() {
  cat <<EOF
Usage:
  .aicrowd/scripts/public-sync.sh [global-options] <command> [command-options]

Global options:
  --state-file <path>      Override local sync state path
  -h, --help               Show this help

Commands:
  status                   Show sync status between internal main and public/main
  mark                     Set LAST_INGESTED_PUBLIC_SHA in local state
  intake                   Cherry-pick new public commits into an intake branch
  publish                  Mirror internal branch to sanitized public history

Examples:
  .aicrowd/scripts/public-sync.sh status
  .aicrowd/scripts/public-sync.sh mark
  .aicrowd/scripts/public-sync.sh intake --mark-ingested
  .aicrowd/scripts/public-sync.sh publish --remote-url https://github.com/AIcrowd/circuit-estimation-challenge-internal.git
EOF
}

load_state() {
  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
  fi
  PUBLIC_REMOTE="${PUBLIC_REMOTE:-public}"
  PUBLIC_BRANCH="${PUBLIC_BRANCH:-main}"
  LAST_INGESTED_PUBLIC_SHA="${LAST_INGESTED_PUBLIC_SHA:-}"
  LAST_SYNC_UTC="${LAST_SYNC_UTC:-}"
}

write_state() {
  mkdir -p "$(dirname "$STATE_FILE")"
  cat > "$STATE_FILE" <<EOF
# Local sync state for internal <-> sanitized-public workflow.
# Generated by .aicrowd/scripts/public-sync.sh
PUBLIC_REMOTE=$PUBLIC_REMOTE
PUBLIC_BRANCH=$PUBLIC_BRANCH
LAST_INGESTED_PUBLIC_SHA=$LAST_INGESTED_PUBLIC_SHA
LAST_SYNC_UTC=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
EOF
}

init_state_if_missing() {
  if [[ -f "$STATE_FILE" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$STATE_FILE")"
  if [[ -f "$STATE_EXAMPLE_FILE" ]]; then
    cp "$STATE_EXAMPLE_FILE" "$STATE_FILE"
  else
    cat > "$STATE_FILE" <<EOF
PUBLIC_REMOTE=public
PUBLIC_BRANCH=main
LAST_INGESTED_PUBLIC_SHA=
LAST_SYNC_UTC=
EOF
  fi
}

require_clean_worktree() {
  if ! git diff --quiet || ! git diff --cached --quiet; then
    die "Working tree is not clean. Commit or stash changes first."
  fi
}

ensure_file_exists() {
  local file="$1"
  [[ -f "$file" ]] || die "Required file is missing: $file"
}

fetch_public() {
  git fetch "$PUBLIC_REMOTE" "$PUBLIC_BRANCH" --prune >/dev/null
}

remove_manifest_paths() {
  local target_dir="$1"
  local raw line

  ensure_file_exists "$SENSITIVE_MANIFEST"

  while IFS= read -r raw; do
    line="$(trim_line "$raw")"
    [[ -z "$line" ]] && continue
    rm -rf "$target_dir/$line"
  done < "$SENSITIVE_MANIFEST"
}

apply_blob_replacements() {
  local target_dir="$1"
  local tmp_matches raw line payload pattern replacement

  [[ -f "$BLOB_REPLACEMENTS" ]] || return 0

  tmp_matches="$(mktemp /tmp/public-sync-rewrite-files-XXXXXX)"
  trap 'rm -f "$tmp_matches"' RETURN

  while IFS= read -r raw; do
    line="$(trim_line "$raw")"
    [[ -z "$line" ]] && continue
    if [[ "$line" == regex:* ]] && [[ "$line" == *"==>"* ]]; then
      payload="${line#regex:}"
      pattern="${payload%%==>*}"
      replacement="${payload#*==>}"
      if rg -l --null --hidden -P -g '!.git/*' "$pattern" "$target_dir" > "$tmp_matches" 2>/dev/null; then
        PATTERN="$pattern" REPLACEMENT="$replacement" \
          xargs -0 perl -0777 -i -pe 'BEGIN{$p=$ENV{PATTERN};$r=$ENV{REPLACEMENT}} s/$p/$r/g' < "$tmp_matches"
      fi
    else
      die "Invalid replacement rule in $BLOB_REPLACEMENTS: $line"
    fi
  done < "$BLOB_REPLACEMENTS"

  rm -f "$tmp_matches"
  trap - RETURN
}

verify_no_sensitive_paths_or_text() {
  local target_dir="$1"
  local raw line leak=0
  local content_regex='(\.aicrowd/|\.agent/|\.agents/|\.codex/|docs/plans|docs/context|CHALLENGE-CONTEXT\.md|worktrees-and-cli\.md|STYLE_GUIDE\.md)'
  local leak_file

  ensure_file_exists "$SENSITIVE_MANIFEST"

  while IFS= read -r raw; do
    line="$(trim_line "$raw")"
    [[ -z "$line" ]] && continue
    if [[ -e "$target_dir/$line" ]]; then
      echo "Sensitive path exists in publish workspace: $line" >&2
      leak=1
    fi
  done < "$SENSITIVE_MANIFEST"

  leak_file="$(mktemp /tmp/public-sync-content-leaks-XXXXXX)"
  if rg -n -I -E --hidden -g '!.git/*' "$content_regex" "$target_dir" > "$leak_file" 2>/dev/null; then
    echo "Sensitive text reference found in publish workspace:" >&2
    cat "$leak_file" >&2
    leak=1
  fi
  rm -f "$leak_file"

  [[ "$leak" -eq 0 ]] || die "Sensitive path/text checks failed."
}

cmd_status() {
  local no_fetch=0 internal_branch="main"
  local ahead behind counts public_sha internal_sha

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --no-fetch)
        no_fetch=1
        shift
        ;;
      --internal-branch)
        internal_branch="$2"
        shift 2
        ;;
      *)
        die "Unknown status option: $1"
        ;;
    esac
  done

  load_state
  if [[ "$no_fetch" -ne 1 ]]; then
    fetch_public
  fi

  public_sha="$(git rev-parse --short "$PUBLIC_REMOTE/$PUBLIC_BRANCH")"
  if git show-ref --verify --quiet "refs/heads/$internal_branch"; then
    internal_sha="$(git rev-parse --short "$internal_branch")"
    counts="$(git rev-list --left-right --count "$internal_branch...$PUBLIC_REMOTE/$PUBLIC_BRANCH")"
    ahead="$(printf '%s' "$counts" | awk '{print $1}')"
    behind="$(printf '%s' "$counts" | awk '{print $2}')"
  else
    internal_sha="(missing)"
    ahead="n/a"
    behind="n/a"
  fi

  echo "State file: $STATE_FILE"
  echo "Public remote/branch: $PUBLIC_REMOTE/$PUBLIC_BRANCH"
  echo "Internal branch: $internal_branch ($internal_sha)"
  echo "Public branch:   $PUBLIC_REMOTE/$PUBLIC_BRANCH ($public_sha)"
  echo "Divergence ($internal_branch...$PUBLIC_REMOTE/$PUBLIC_BRANCH): ahead=$ahead behind=$behind"
  echo "LAST_INGESTED_PUBLIC_SHA: ${LAST_INGESTED_PUBLIC_SHA:-<unset>}"
  echo "LAST_SYNC_UTC: ${LAST_SYNC_UTC:-<unset>}"

  if [[ -n "$LAST_INGESTED_PUBLIC_SHA" ]]; then
    if [[ "$LAST_INGESTED_PUBLIC_SHA" == "$(git rev-parse "$PUBLIC_REMOTE/$PUBLIC_BRANCH")" ]]; then
      echo "Marker check: OK (ingested marker matches current public tip)"
    else
      echo "Marker check: OUT-OF-DATE (ingest required before publish)"
    fi
  else
    echo "Marker check: UNSET (run 'mark' after validating baseline)"
  fi
}

cmd_mark() {
  local target_sha=""
  local no_fetch=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --sha)
        target_sha="$2"
        shift 2
        ;;
      --no-fetch)
        no_fetch=1
        shift
        ;;
      *)
        die "Unknown mark option: $1"
        ;;
    esac
  done

  init_state_if_missing
  load_state
  if [[ "$no_fetch" -ne 1 ]]; then
    fetch_public
  fi

  if [[ -z "$target_sha" ]]; then
    target_sha="$(git rev-parse "$PUBLIC_REMOTE/$PUBLIC_BRANCH")"
  fi
  git rev-parse --verify "$target_sha^{commit}" >/dev/null

  LAST_INGESTED_PUBLIC_SHA="$target_sha"
  write_state
  echo "Updated LAST_INGESTED_PUBLIC_SHA to $LAST_INGESTED_PUBLIC_SHA"
  echo "State file: $STATE_FILE"
}

cmd_intake() {
  local base_branch="main"
  local branch_name=""
  local start_sha=""
  local dry_run=0
  local mark_ingested=0
  local no_branch=0
  local end_sha

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --base-branch)
        base_branch="$2"
        shift 2
        ;;
      --branch-name)
        branch_name="$2"
        shift 2
        ;;
      --start-sha)
        start_sha="$2"
        shift 2
        ;;
      --dry-run)
        dry_run=1
        shift
        ;;
      --mark-ingested)
        mark_ingested=1
        shift
        ;;
      --no-branch)
        no_branch=1
        shift
        ;;
      *)
        die "Unknown intake option: $1"
        ;;
    esac
  done

  init_state_if_missing
  load_state
  require_clean_worktree
  fetch_public

  end_sha="$(git rev-parse "$PUBLIC_REMOTE/$PUBLIC_BRANCH")"
  if [[ -z "$start_sha" ]]; then
    start_sha="$LAST_INGESTED_PUBLIC_SHA"
  fi
  [[ -n "$start_sha" ]] || die "No start SHA provided and LAST_INGESTED_PUBLIC_SHA is unset. Run: public-sync.sh mark"

  git rev-parse --verify "$start_sha^{commit}" >/dev/null
  if ! git merge-base --is-ancestor "$start_sha" "$end_sha"; then
    die "Start SHA is not an ancestor of $PUBLIC_REMOTE/$PUBLIC_BRANCH. Re-baseline with: public-sync.sh mark --sha <public-sha>"
  fi
  if [[ "$start_sha" == "$end_sha" ]]; then
    echo "No new commits to intake. Marker already at public tip."
    return 0
  fi

  echo "Public commits to intake:"
  git log --reverse --oneline "$start_sha..$end_sha"

  if [[ "$dry_run" -eq 1 ]]; then
    echo "Dry-run only. No cherry-pick performed."
    return 0
  fi

  if [[ "$no_branch" -ne 1 ]]; then
    if [[ -z "$branch_name" ]]; then
      branch_name="sync/public-intake-$(date -u '+%Y%m%d-%H%M%S')"
    fi
    git switch -c "$branch_name" "$base_branch"
    echo "Created intake branch: $branch_name (from $base_branch)"
  fi

  if ! git cherry-pick "$start_sha..$end_sha"; then
    cat <<EOF >&2
Cherry-pick failed.
Resolve conflicts, then run:
  git cherry-pick --continue
or abort with:
  git cherry-pick --abort
EOF
    exit 1
  fi

  echo "Intake cherry-pick completed."
  if [[ "$mark_ingested" -eq 1 ]]; then
    LAST_INGESTED_PUBLIC_SHA="$end_sha"
    write_state
    echo "Updated ingestion marker to $LAST_INGESTED_PUBLIC_SHA"
  else
    echo "Marker not updated. After merge, run:"
    echo "  .aicrowd/scripts/public-sync.sh mark --sha $end_sha"
  fi
}

cmd_publish() {
  local source_branch="main"
  local commit_message="sync: mirror internal updates"
  local workdir=""
  local keep_workdir=0
  local allow_uningested=0
  local dry_run=0
  local remote_url=""
  local baseline_public_sha
  local cleanup=1
  local source_snapshot
  local work_repo
  local pushed_sha=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --source-branch)
        source_branch="$2"
        shift 2
        ;;
      --message)
        commit_message="$2"
        shift 2
        ;;
      --workdir)
        workdir="$2"
        shift 2
        ;;
      --keep-workdir)
        keep_workdir=1
        shift
        ;;
      --allow-uningested)
        allow_uningested=1
        shift
        ;;
      --dry-run)
        dry_run=1
        shift
        ;;
      --remote-url)
        remote_url="$2"
        shift 2
        ;;
      *)
        die "Unknown publish option: $1"
        ;;
    esac
  done

  ensure_file_exists "$EXCLUDE_FILE"
  ensure_file_exists "$SENSITIVE_MANIFEST"
  require_clean_worktree
  init_state_if_missing
  load_state
  fetch_public

  baseline_public_sha="$(git rev-parse "$PUBLIC_REMOTE/$PUBLIC_BRANCH")"
  if [[ "$allow_uningested" -ne 1 ]]; then
    [[ -n "$LAST_INGESTED_PUBLIC_SHA" ]] || die "LAST_INGESTED_PUBLIC_SHA is unset. Run: public-sync.sh mark"
    [[ "$LAST_INGESTED_PUBLIC_SHA" == "$baseline_public_sha" ]] || die \
      "Public has un-ingested commits ($PUBLIC_REMOTE/$PUBLIC_BRANCH at $baseline_public_sha, marker at $LAST_INGESTED_PUBLIC_SHA). Run intake first."
  fi

  git show-ref --verify --quiet "refs/heads/$source_branch" || die "Source branch does not exist: $source_branch"

  if [[ "$dry_run" -ne 1 && -z "$remote_url" ]]; then
    die "Publish requires an explicit target via --remote-url <url>."
  fi
  if [[ -z "$remote_url" ]]; then
    remote_url="$(git remote get-url "$PUBLIC_REMOTE")"
  fi

  if [[ -z "$workdir" ]]; then
    workdir="$(mktemp -d /tmp/cestim-public-sync-XXXXXX)"
  else
    mkdir -p "$workdir"
    cleanup=0
  fi
  if [[ "$keep_workdir" -eq 1 ]]; then
    cleanup=0
  fi
  if [[ "$cleanup" -eq 1 ]]; then
    trap "rm -rf '$workdir'" EXIT
  fi

  source_snapshot="$workdir/source"
  work_repo="$workdir/public"
  mkdir -p "$source_snapshot"

  echo "Preparing publish workspace in: $workdir"
  git clone --single-branch --branch "$PUBLIC_BRANCH" "$remote_url" "$work_repo" >/dev/null
  git archive "$source_branch" | tar -x -C "$source_snapshot"

  command -v rsync >/dev/null 2>&1 || die "rsync is required for publish."
  rsync -a --delete --exclude-from "$EXCLUDE_FILE" "$source_snapshot"/ "$work_repo"/
  remove_manifest_paths "$work_repo"
  apply_blob_replacements "$work_repo"
  verify_no_sensitive_paths_or_text "$work_repo"

  (
    cd "$work_repo"
    git add -A
    if git diff --cached --quiet; then
      echo "No publishable changes after sanitization."
      exit 0
    fi

    git commit -m "$commit_message" >/dev/null
    pushed_sha="$(git rev-parse HEAD)"
    echo "Prepared public commit: $pushed_sha"

    if [[ "$dry_run" -eq 1 ]]; then
      echo "Dry-run only. Not pushing."
      exit 0
    fi

    git push origin "HEAD:$PUBLIC_BRANCH"
    pushed_sha="$(git ls-remote origin "refs/heads/$PUBLIC_BRANCH" | awk '{print $1}')"
    echo "Pushed to $remote_url:$PUBLIC_BRANCH at $pushed_sha"
  )

  if [[ "$dry_run" -ne 1 ]]; then
    pushed_sha="$(git ls-remote "$remote_url" "refs/heads/$PUBLIC_BRANCH" | awk '{print $1}')"
    [[ -n "$pushed_sha" ]] || die "Could not resolve pushed public SHA for $PUBLIC_BRANCH at $remote_url"
    LAST_INGESTED_PUBLIC_SHA="$pushed_sha"
    write_state
    echo "Updated ingestion marker to $LAST_INGESTED_PUBLIC_SHA"
  fi

  if [[ "$cleanup" -eq 0 ]]; then
    echo "Kept publish workspace: $workdir"
  fi
}

main() {
  local cmd=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --state-file)
        STATE_FILE="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      status|mark|intake|publish)
        cmd="$1"
        shift
        break
        ;;
      *)
        die "Unknown option or command: $1"
        ;;
    esac
  done

  [[ -n "$cmd" ]] || {
    usage
    exit 2
  }

  case "$cmd" in
    status)  cmd_status "$@" ;;
    mark)    cmd_mark "$@" ;;
    intake)  cmd_intake "$@" ;;
    publish) cmd_publish "$@" ;;
    *) die "Unhandled command: $cmd" ;;
  esac
}

main "$@"
